GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA org TO app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA content TO app;
GRANT USAGE, SELECT, UPDATE ON ALL SEQUENCES IN SCHEMA sync TO app;

ALTER DEFAULT PRIVILEGES IN SCHEMA org
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO app;

ALTER DEFAULT PRIVILEGES IN SCHEMA content
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO app;

ALTER DEFAULT PRIVILEGES IN SCHEMA sync
  GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO app;
