-- Migration status: Current / canonical.
-- Introduces: the current sync architecture with hot mutable state, separate review-history cursors, and direct bootstrap from canonical tables.
-- Current guidance: this is the canonical sync migration and replaces the earlier sync.changes global-feed model and its dependent follow-ups.
-- Replaces or corrects: db/migrations/0007_global_sync_changes.sql, db/migrations/0010_normalize_sync_change_timestamps.sql, sync-related parts of db/migrations/0018_auto_provision_workspaces_and_scheduler_seed.sql, sync-related parts of db/migrations/0027_sync_card_created_at_and_device_rls.sql, sync.applied_operations policy assumptions in db/migrations/0024_auth_runtime_roles.sql.
-- Ordering note: migration filenames execute lexicographically, so db/migrations/0028_created_at_ordering_indexes.sql runs before db/migrations/0028_sync_hot_state_rewrite.sql.
-- See also: docs/architecture.md.
-- Replace the legacy global replay log with separate hot-state and review
-- history sync lanes. Current-state bootstrap now reads canonical tables
-- directly, while incremental pull reads a compact metadata-only hot log.

-- Review history now advances on its own append-only cursor instead of
-- piggy-backing on the mutable hot-state feed.
ALTER TABLE content.review_events
  ADD COLUMN IF NOT EXISTS review_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY;

CREATE INDEX IF NOT EXISTS idx_review_events_workspace_review_sequence
  ON content.review_events(workspace_id, review_sequence);

COMMENT ON COLUMN content.review_events.review_sequence IS 'Monotonic append-only review-history cursor used by sync/review-history/pull.';

-- Workspace-level sync metadata keeps retention and bootstrap state explicit.
CREATE TABLE IF NOT EXISTS sync.workspace_sync_metadata (
  workspace_id UUID PRIMARY KEY REFERENCES org.workspaces(workspace_id) ON DELETE CASCADE,
  min_available_hot_change_id BIGINT NOT NULL DEFAULT 0,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE sync.workspace_sync_metadata IS 'Workspace-scoped sync metadata such as the oldest hot cursor still available for incremental pull.';
COMMENT ON COLUMN sync.workspace_sync_metadata.min_available_hot_change_id IS 'Oldest hot cursor still available for this workspace. Older clients must re-bootstrap.';

-- Compact mutable-root hot log. It keeps only identity and LWW metadata, not
-- full JSON snapshots or append-only review history.
CREATE TABLE IF NOT EXISTS sync.hot_changes (
  change_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  workspace_id UUID NOT NULL REFERENCES org.workspaces(workspace_id) ON DELETE CASCADE,
  entity_type TEXT NOT NULL CHECK (entity_type IN ('card', 'deck', 'workspace_scheduler_settings')),
  entity_id TEXT NOT NULL,
  action TEXT NOT NULL CHECK (action IN ('upsert')),
  device_id UUID NOT NULL REFERENCES sync.devices(device_id) ON DELETE RESTRICT,
  operation_id TEXT NOT NULL,
  client_updated_at TIMESTAMPTZ NOT NULL,
  recorded_at TIMESTAMPTZ NOT NULL DEFAULT now()
) PARTITION BY RANGE (recorded_at);

CREATE TABLE IF NOT EXISTS sync.hot_changes_2026
  PARTITION OF sync.hot_changes
  FOR VALUES FROM ('2026-01-01 00:00:00+00') TO ('2027-01-01 00:00:00+00');

CREATE TABLE IF NOT EXISTS sync.hot_changes_2027
  PARTITION OF sync.hot_changes
  FOR VALUES FROM ('2027-01-01 00:00:00+00') TO ('2028-01-01 00:00:00+00');

CREATE TABLE IF NOT EXISTS sync.hot_changes_default
  PARTITION OF sync.hot_changes DEFAULT;

CREATE INDEX IF NOT EXISTS idx_hot_changes_workspace_change_id
  ON sync.hot_changes(workspace_id, change_id);

CREATE INDEX IF NOT EXISTS idx_hot_changes_workspace_entity_latest
  ON sync.hot_changes(workspace_id, entity_type, entity_id, change_id DESC);

COMMENT ON TABLE sync.hot_changes IS 'Compact hot-state mutation log for mutable sync roots only. Bootstrap reads canonical tables directly.';
COMMENT ON COLUMN sync.hot_changes.client_updated_at IS 'Client-provided LWW timestamp of the winning mutable mutation.';

-- Bounded idempotency ledger for batched push requests.
CREATE TABLE IF NOT EXISTS sync.applied_operations_current (
  workspace_id UUID NOT NULL REFERENCES org.workspaces(workspace_id) ON DELETE CASCADE,
  device_id UUID NOT NULL REFERENCES sync.devices(device_id) ON DELETE RESTRICT,
  operation_id TEXT NOT NULL,
  operation_type TEXT NOT NULL,
  entity_type TEXT NOT NULL CHECK (entity_type IN ('card', 'deck', 'workspace_scheduler_settings', 'review_event')),
  entity_id TEXT NOT NULL,
  client_updated_at TIMESTAMPTZ NOT NULL,
  resulting_hot_change_id BIGINT,
  applied_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (workspace_id, device_id, operation_id, applied_at)
) PARTITION BY RANGE (applied_at);

CREATE TABLE IF NOT EXISTS sync.applied_operations_current_2026
  PARTITION OF sync.applied_operations_current
  FOR VALUES FROM ('2026-01-01 00:00:00+00') TO ('2027-01-01 00:00:00+00');

CREATE TABLE IF NOT EXISTS sync.applied_operations_current_2027
  PARTITION OF sync.applied_operations_current
  FOR VALUES FROM ('2027-01-01 00:00:00+00') TO ('2028-01-01 00:00:00+00');

CREATE TABLE IF NOT EXISTS sync.applied_operations_current_default
  PARTITION OF sync.applied_operations_current DEFAULT;

CREATE INDEX IF NOT EXISTS idx_applied_operations_current_workspace_device_operation
  ON sync.applied_operations_current(workspace_id, device_id, operation_id, applied_at DESC);

COMMENT ON TABLE sync.applied_operations_current IS 'Bounded idempotency ledger for sync/push batches after the hot-state rewrite.';

ALTER TABLE sync.workspace_sync_metadata ENABLE ROW LEVEL SECURITY;
ALTER TABLE sync.hot_changes ENABLE ROW LEVEL SECURITY;
ALTER TABLE sync.applied_operations_current ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS workspace_sync_metadata_scoped_select_runtime ON sync.workspace_sync_metadata;
DROP POLICY IF EXISTS workspace_sync_metadata_scoped_insert_runtime ON sync.workspace_sync_metadata;
DROP POLICY IF EXISTS workspace_sync_metadata_scoped_update_runtime ON sync.workspace_sync_metadata;
DROP POLICY IF EXISTS workspace_sync_metadata_scoped_delete_runtime ON sync.workspace_sync_metadata;

CREATE POLICY workspace_sync_metadata_scoped_select_runtime
  ON sync.workspace_sync_metadata
  FOR SELECT
  TO backend_app
  USING (security.current_workspace_access_allowed(workspace_id));

CREATE POLICY workspace_sync_metadata_scoped_insert_runtime
  ON sync.workspace_sync_metadata
  FOR INSERT
  TO backend_app
  WITH CHECK (security.current_workspace_access_allowed(workspace_id));

CREATE POLICY workspace_sync_metadata_scoped_update_runtime
  ON sync.workspace_sync_metadata
  FOR UPDATE
  TO backend_app
  USING (security.current_workspace_access_allowed(workspace_id))
  WITH CHECK (security.current_workspace_access_allowed(workspace_id));

CREATE POLICY workspace_sync_metadata_scoped_delete_runtime
  ON sync.workspace_sync_metadata
  FOR DELETE
  TO backend_app
  USING (security.current_workspace_access_allowed(workspace_id));

DROP POLICY IF EXISTS hot_changes_scoped_select_runtime ON sync.hot_changes;
DROP POLICY IF EXISTS hot_changes_scoped_insert_runtime ON sync.hot_changes;
DROP POLICY IF EXISTS hot_changes_scoped_update_runtime ON sync.hot_changes;
DROP POLICY IF EXISTS hot_changes_scoped_delete_runtime ON sync.hot_changes;

CREATE POLICY hot_changes_scoped_select_runtime
  ON sync.hot_changes
  FOR SELECT
  TO backend_app
  USING (security.current_workspace_access_allowed(workspace_id));

CREATE POLICY hot_changes_scoped_insert_runtime
  ON sync.hot_changes
  FOR INSERT
  TO backend_app
  WITH CHECK (security.current_workspace_access_allowed(workspace_id));

CREATE POLICY hot_changes_scoped_update_runtime
  ON sync.hot_changes
  FOR UPDATE
  TO backend_app
  USING (security.current_workspace_access_allowed(workspace_id))
  WITH CHECK (security.current_workspace_access_allowed(workspace_id));

CREATE POLICY hot_changes_scoped_delete_runtime
  ON sync.hot_changes
  FOR DELETE
  TO backend_app
  USING (security.current_workspace_access_allowed(workspace_id));

DROP POLICY IF EXISTS applied_operations_current_scoped_select_runtime ON sync.applied_operations_current;
DROP POLICY IF EXISTS applied_operations_current_scoped_insert_runtime ON sync.applied_operations_current;
DROP POLICY IF EXISTS applied_operations_current_scoped_update_runtime ON sync.applied_operations_current;
DROP POLICY IF EXISTS applied_operations_current_scoped_delete_runtime ON sync.applied_operations_current;

CREATE POLICY applied_operations_current_scoped_select_runtime
  ON sync.applied_operations_current
  FOR SELECT
  TO backend_app
  USING (security.current_workspace_access_allowed(workspace_id));

CREATE POLICY applied_operations_current_scoped_insert_runtime
  ON sync.applied_operations_current
  FOR INSERT
  TO backend_app
  WITH CHECK (security.current_workspace_access_allowed(workspace_id));

CREATE POLICY applied_operations_current_scoped_update_runtime
  ON sync.applied_operations_current
  FOR UPDATE
  TO backend_app
  USING (security.current_workspace_access_allowed(workspace_id))
  WITH CHECK (security.current_workspace_access_allowed(workspace_id));

CREATE POLICY applied_operations_current_scoped_delete_runtime
  ON sync.applied_operations_current
  FOR DELETE
  TO backend_app
  USING (security.current_workspace_access_allowed(workspace_id));

-- The new bootstrap path reads canonical tables directly, so the legacy
-- replay log is now dead weight and must not survive the cutover.
DROP TABLE IF EXISTS sync.changes CASCADE;
DROP TABLE IF EXISTS sync.applied_operations CASCADE;
