#!/bin/sh

set -eu

if [ "${CI_XCODE_CLOUD:-}" != "TRUE" ]; then
  exit 0
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
LOCAL_XCCONFIG_PATH="${PROJECT_DIR}/Config/Local.xcconfig"

if [ -z "${XCODE_CLOUD_DEVELOPMENT_TEAM:-}" ] \
  && [ -z "${XCODE_CLOUD_APP_BUNDLE_IDENTIFIER:-}" ] \
  && [ -z "${XCODE_CLOUD_API_BASE_URL:-}" ] \
  && [ -z "${XCODE_CLOUD_AUTH_BASE_URL:-}" ]; then
  echo "Xcode Cloud override variables are not set. Skipping Local.xcconfig generation."
  exit 0
fi

cat > "${LOCAL_XCCONFIG_PATH}" <<EOF
// Generated by ci_scripts/ci_post_clone.sh in Xcode Cloud.
// Do not commit this file. Regenerate it from workflow environment variables.
EOF

if [ -n "${XCODE_CLOUD_DEVELOPMENT_TEAM:-}" ]; then
  printf 'DEVELOPMENT_TEAM = %s\n' "${XCODE_CLOUD_DEVELOPMENT_TEAM}" >> "${LOCAL_XCCONFIG_PATH}"
fi

if [ -n "${XCODE_CLOUD_APP_BUNDLE_IDENTIFIER:-}" ]; then
  printf 'APP_BUNDLE_IDENTIFIER = %s\n' "${XCODE_CLOUD_APP_BUNDLE_IDENTIFIER}" >> "${LOCAL_XCCONFIG_PATH}"
fi

if [ -n "${XCODE_CLOUD_API_BASE_URL:-}" ]; then
  printf 'API_BASE_URL = %s\n' "${XCODE_CLOUD_API_BASE_URL}" >> "${LOCAL_XCCONFIG_PATH}"
fi

if [ -n "${XCODE_CLOUD_AUTH_BASE_URL:-}" ]; then
  printf 'AUTH_BASE_URL = %s\n' "${XCODE_CLOUD_AUTH_BASE_URL}" >> "${LOCAL_XCCONFIG_PATH}"
fi

echo "Generated ${LOCAL_XCCONFIG_PATH} for Xcode Cloud."
