#!/bin/sh

set -eu

if [ "${CI_XCODE_CLOUD:-}" != "TRUE" ]; then
  exit 0
fi

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
PROJECT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
LOCAL_XCCONFIG_PATH="${PROJECT_DIR}/Config/Local.xcconfig"
REQUIRED_URL_PREFIX='https:/$()/'

append_missing_key() {
  key="$1"

  if [ -n "${MISSING_KEYS}" ]; then
    MISSING_KEYS="${MISSING_KEYS}, ${key}"
    return
  fi

  MISSING_KEYS="${key}"
}

validate_required_value() {
  key="$1"
  value="$2"

  if [ -n "${value}" ]; then
    return
  fi

  append_missing_key "${key}"
}

validate_required_url_value() {
  key="$1"
  value="$2"

  case "${value}" in
    "${REQUIRED_URL_PREFIX}"*)
      return
      ;;
    *)
      echo "Xcode Cloud environment variable ${key} must start with ${REQUIRED_URL_PREFIX}. Received: ${value}" >&2
      exit 1
      ;;
  esac
}

XCODE_CLOUD_DEVELOPMENT_TEAM_VALUE="${XCODE_CLOUD_DEVELOPMENT_TEAM:-}"
XCODE_CLOUD_APP_BUNDLE_IDENTIFIER_VALUE="${XCODE_CLOUD_APP_BUNDLE_IDENTIFIER:-}"
XCODE_CLOUD_API_BASE_URL_VALUE="${XCODE_CLOUD_API_BASE_URL:-}"
XCODE_CLOUD_AUTH_BASE_URL_VALUE="${XCODE_CLOUD_AUTH_BASE_URL:-}"
XCODE_CLOUD_PRIVACY_POLICY_URL_VALUE="${XCODE_CLOUD_PRIVACY_POLICY_URL:-}"
XCODE_CLOUD_TERMS_OF_SERVICE_URL_VALUE="${XCODE_CLOUD_TERMS_OF_SERVICE_URL:-}"
XCODE_CLOUD_SUPPORT_URL_VALUE="${XCODE_CLOUD_SUPPORT_URL:-}"
XCODE_CLOUD_SUPPORT_EMAIL_ADDRESS_VALUE="${XCODE_CLOUD_SUPPORT_EMAIL_ADDRESS:-}"
MISSING_KEYS=""

# Xcode Cloud is the canonical signed archive path. It writes release-only
# signing and production host overrides into the gitignored Local.xcconfig.
validate_required_value "XCODE_CLOUD_DEVELOPMENT_TEAM" "${XCODE_CLOUD_DEVELOPMENT_TEAM_VALUE}"
validate_required_value "XCODE_CLOUD_APP_BUNDLE_IDENTIFIER" "${XCODE_CLOUD_APP_BUNDLE_IDENTIFIER_VALUE}"
validate_required_value "XCODE_CLOUD_API_BASE_URL" "${XCODE_CLOUD_API_BASE_URL_VALUE}"
validate_required_value "XCODE_CLOUD_AUTH_BASE_URL" "${XCODE_CLOUD_AUTH_BASE_URL_VALUE}"
validate_required_value "XCODE_CLOUD_PRIVACY_POLICY_URL" "${XCODE_CLOUD_PRIVACY_POLICY_URL_VALUE}"
validate_required_value "XCODE_CLOUD_TERMS_OF_SERVICE_URL" "${XCODE_CLOUD_TERMS_OF_SERVICE_URL_VALUE}"
validate_required_value "XCODE_CLOUD_SUPPORT_URL" "${XCODE_CLOUD_SUPPORT_URL_VALUE}"
validate_required_value "XCODE_CLOUD_SUPPORT_EMAIL_ADDRESS" "${XCODE_CLOUD_SUPPORT_EMAIL_ADDRESS_VALUE}"

if [ -n "${MISSING_KEYS}" ]; then
  echo "Xcode Cloud requires these workflow environment variables before build: ${MISSING_KEYS}" >&2
  exit 1
fi

validate_required_url_value "XCODE_CLOUD_API_BASE_URL" "${XCODE_CLOUD_API_BASE_URL_VALUE}"
validate_required_url_value "XCODE_CLOUD_AUTH_BASE_URL" "${XCODE_CLOUD_AUTH_BASE_URL_VALUE}"
validate_required_url_value "XCODE_CLOUD_PRIVACY_POLICY_URL" "${XCODE_CLOUD_PRIVACY_POLICY_URL_VALUE}"
validate_required_url_value "XCODE_CLOUD_TERMS_OF_SERVICE_URL" "${XCODE_CLOUD_TERMS_OF_SERVICE_URL_VALUE}"
validate_required_url_value "XCODE_CLOUD_SUPPORT_URL" "${XCODE_CLOUD_SUPPORT_URL_VALUE}"

cat > "${LOCAL_XCCONFIG_PATH}" <<EOF
// Generated by ci_scripts/ci_post_clone.sh in Xcode Cloud.
// Do not commit this file. Regenerate it from workflow environment variables.
EOF

printf 'DEVELOPMENT_TEAM = %s\n' "${XCODE_CLOUD_DEVELOPMENT_TEAM_VALUE}" >> "${LOCAL_XCCONFIG_PATH}"
printf 'APP_BUNDLE_IDENTIFIER = %s\n' "${XCODE_CLOUD_APP_BUNDLE_IDENTIFIER_VALUE}" >> "${LOCAL_XCCONFIG_PATH}"
printf 'API_BASE_URL = %s\n' "${XCODE_CLOUD_API_BASE_URL_VALUE}" >> "${LOCAL_XCCONFIG_PATH}"
printf 'AUTH_BASE_URL = %s\n' "${XCODE_CLOUD_AUTH_BASE_URL_VALUE}" >> "${LOCAL_XCCONFIG_PATH}"
printf 'PRIVACY_POLICY_URL = %s\n' "${XCODE_CLOUD_PRIVACY_POLICY_URL_VALUE}" >> "${LOCAL_XCCONFIG_PATH}"
printf 'TERMS_OF_SERVICE_URL = %s\n' "${XCODE_CLOUD_TERMS_OF_SERVICE_URL_VALUE}" >> "${LOCAL_XCCONFIG_PATH}"
printf 'SUPPORT_URL = %s\n' "${XCODE_CLOUD_SUPPORT_URL_VALUE}" >> "${LOCAL_XCCONFIG_PATH}"
printf 'SUPPORT_EMAIL_ADDRESS = %s\n' "${XCODE_CLOUD_SUPPORT_EMAIL_ADDRESS_VALUE}" >> "${LOCAL_XCCONFIG_PATH}"

echo "Generated ${LOCAL_XCCONFIG_PATH} for Xcode Cloud."
