package com.flashcardsopensourceapp.feature.ai

const val aiEmptyStateTag: String = "ai_empty_state"
const val aiEmptyStateContentTag: String = "ai_empty_state_content"
const val aiConversationLoadingTag: String = "ai_conversation_loading"
const val aiConversationSurfaceTag: String = "ai_conversation_surface"
const val aiNewChatButtonTag: String = "ai_new_chat_button"
const val aiComposerMessageFieldTag: String = "ai_composer_message_field"
const val aiComposerPendingAttachmentTag: String = "ai_composer_pending_attachment"
const val aiComposerSendButtonTag: String = "ai_composer_send_button"
const val aiComposerSuggestionRowTag: String = "ai_composer_suggestion_row"
const val aiComposerSuggestionPrefixTag: String = "ai_composer_suggestion_"
const val aiToolCallCardTag: String = "ai_tool_call_card"
const val aiToolCallSummaryTag: String = "ai_tool_call_summary"
const val aiToolCallStatusTag: String = "ai_tool_call_status"
const val aiToolCallInputTag: String = "ai_tool_call_input"
const val aiToolCallOutputTag: String = "ai_tool_call_output"
const val aiToolCallExpandButtonTag: String = "ai_tool_call_expand_button"
const val aiAssistantMessageBubbleTag: String = "ai_assistant_message_bubble"
const val aiAssistantTextPartTag: String = "ai_assistant_text_part"
const val aiUserMessageBubbleTag: String = "ai_user_message_bubble"
